"use client";
// QAPanel.tsx — "Ask the Reporter" conversational Q&A panel
import { useState } from 'react';
import { fetchArticleQA } from '../api';

interface Props {
  articleId: number;
}

const SUGGESTED = [
  'What are the key facts here?',
  'Who are the main parties involved?',
  'What happens next?',
];

export default function QAPanel({ articleId }: Props) {
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const ask = async (q: string) => {
    if (!q.trim() || loading) return;
    setLoading(true);
    setError(null);
    setAnswer(null);
    try {
      const result = await fetchArticleQA(articleId, q.trim());
      setAnswer(result.answer);
    } catch {
      setError('The AI reporter couldn\'t answer right now — please try again shortly.');
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    ask(question);
  };

  return (
    <div className="qa-panel">
      <div className="prov-section-title">Ask the Reporter</div>

      {/* Suggested questions */}
      {!answer && !loading && (
        <div className="qa-suggestions">
          {SUGGESTED.map(s => (
            <button
              key={s}
              className="qa-suggestion-chip"
              onClick={() => { setQuestion(s); ask(s); }}
            >
              {s}
            </button>
          ))}
        </div>
      )}

      <form className="qa-form" onSubmit={handleSubmit}>
        <textarea
          className="qa-input"
          placeholder="Ask a question about this story…"
          value={question}
          onChange={e => setQuestion(e.target.value)}
          rows={2}
          disabled={loading}
          id={`qa-input-${articleId}`}
          onKeyDown={e => {
            if (e.key === 'Enter' && !e.shiftKey) {
              e.preventDefault();
              ask(question);
            }
          }}
        />
        <button
          className="qa-submit"
          type="submit"
          disabled={loading || !question.trim()}
          id={`qa-submit-${articleId}`}
        >
          {loading ? (
            <span className="qa-spinner" />
          ) : 'Ask'}
        </button>
      </form>

      {loading && (
        <div className="qa-thinking">
          <span className="qa-thinking-dot" />
          <span className="qa-thinking-dot" />
          <span className="qa-thinking-dot" />
          <span style={{ marginLeft: 8, fontSize: 11, color: 'var(--text-muted)' }}>
            Reporter is answering…
          </span>
        </div>
      )}

      {answer && (
        <div className="qa-answer">
          <div className="qa-answer-label">Reporter's Answer</div>
          <p className="qa-answer-text">{answer}</p>
          <button
            className="qa-ask-another"
            onClick={() => { setAnswer(null); setQuestion(''); }}
          >
            Ask another question
          </button>
        </div>
      )}

      {error && <div className="qa-error">{error}</div>}

      <p className="qa-disclaimer">
        Answers are generated by AI from the article content only.
      </p>
    </div>
  );
}
